### ISSUE TITLE
Functionname "catch" fails YUICompressor

### ISSUE THREAD

**Issue by ivome** [KyleAMathews/superagent-bluebird-promise#19]
The YUiCompressor does not like the catch function name and fails compressing the file and interprets it as a reserved keyword. Ideally that should be fixed in yuicompressor itself, but it does not seem to be trivial there, [the issue](https://github.com/yui/yuicompressor/issues/47) is open for quite a while now. 
So easy fix would be to just call the function like that: `['catch']()`

**Comment by KyleAMathews** [comment]
I merged your commit :)

https://github.com/KyleAMathews/superagent-bluebird-promise/pull/20

**Comment by KyleAMathews** [comment]
Released 2.0.1

**Comment by herau** [comment]
i don't find any information about this fix in the release note (and also no information about a 2.0.1 release). 

Can you please tell me what is the release which contains the fix ?

Thanks
