### ISSUE TITLE
Automatic promisification

### ISSUE THREAD

**Issue by benjamingr** [KyleAMathews/superagent-bluebird-promise#24]
Hey - just wondering why this doesn't use `promisify` and uses the promise constructor instead.

**Comment by KyleAMathews** [comment]
I don't know :) I'm not an expert actually on Promises (despite having started this project (which was shamelessly stolen from a gist)). Can you sketch out how promisify works and the advantages it offers over our current approach?

**Comment by benjamingr** [comment]
`promisify` takes a function and returns a promise returning function of it automatically.

http://bluebirdjs.com/docs/api/promisification.html

**Comment by KyleAMathews** [comment]
So it's basically a shortcut then. Well... I'd prefer to be explicit over using magic. `promisify` seems more suitable for writing application code than a library where you want to be sure you're doing things correctly.
