### ISSUE TITLE
How to bind a callback?

### ISSUE THREAD

**Issue by mbrevda** [KyleAMathews/superagent-bluebird-promise#27]
With the following code, I have tired binding the context to `this`:
```js
rest.get('myUrl').then(function(res){
    // do something with this
})
```

But regardless of how I do it, the function doesnt see this.anything. I have tired with `function(){}.bind()` as well as `rest.get('myUrl').bind().then()`.

edit: I also tried `rest.get('myUrl').promise().bind().then()`.

Any ideas?

**Comment by markdalgleish** [comment]
Can I ask why your callback needs context? What are you expecting `this` to be?

**Comment by mbrevda** [comment]
I have an object with a list of urls. Need to fetch the url and update the object with data received.

**Comment by KyleAMathews** [comment]
You can always fall back on creating an alias to your `this` e.g.

```javascript
var self = this;
rest.get('myUrl').then(function(res){
    self.doWhatever()
})
```

**Comment by mbrevda** [comment]
thats exactly the issue I was trying to work around to begin with - those variables didnt show up!

**Comment by KyleAMathews** [comment]
`self` doesn't? Can you paste your full code here?

**Comment by mbrevda** [comment]
I've tried again using a local variable:

```js
var rest = require('superagent-bluebird-promise')

var foo = function() {
    var iList = [/*list details here*/]
    for (var i = 0; i < iList.length; i++) {
        rest.get(
            'myUrl/' + iList[i].location
        ).then(function(res){
            var imageName = path.basename(iList[i].location)
            //and some more stuff here
        })
    }
}
```

and the error im getting is `Unhandled rejection TypeError: Cannot read property 'location' of undefined`. This error only apears for the callback, not for the initial rest call.

Thanks!

**Comment by KyleAMathews** [comment]
Ah, that's a slightly different problem. "Unhandled rejection" means you haven't added yet a "catch" function to catch the error that's being thrown. Try adding `.catch(function(err) { console.log(err) })` after the `.then`.

**Comment by mbrevda** [comment]
Hmm, so that is, indeed a bit better for error handling, but Im still getting the same error message:
`[TypeError: Cannot read property 'location' of undefined]`

**Comment by KyleAMathews** [comment]
That looks like a problem with your code now. Apparently iList[i] turns up
empty objects at times.

**Comment by mbrevda** [comment]
The same variable (`iList[i]`) works just fine for the get() call, so I dont think thats the issue

**Comment by mbrevda** [comment]
The issue and a solution: http://stackoverflow.com/questions/25325037/how-can-i-store-the-count-of-a-for-loop-with-promises-that-return-in-an-arbitrar
