### ISSUE TITLE
Question: any way to implement behavior similar to superagent-intercept?

### ISSUE THREAD

**Issue by kwhitaker** [KyleAMathews/superagent-bluebird-promise#28]
I need to do some 401 checking on every request to an API.  There's a library to do this for vanilla superagent, https://github.com/codesuki/superagent-intercept, but the expectations are of course different for your library.

Is there a recommended way to implement something similar for this library?

Thanks.

**Comment by KyleAMathews** [comment]
After a quick glance at `superagent-intercept`, I don't see why you couldn't use both that and this module together. `superagent-bluebird-promise` just waits for `req.end` to be called so using intercept to do some 401 checking *shouldn't* cause any trouble. Try it and see?

**Comment by kwhitaker** [comment]
I've tried loading it in - and it looks like there's an expectation with SuperAgent that isn't being met. Using the interceptor throws an error - I'll try and get more details for you.

**Comment by kwhitaker** [comment]
Looks like the problem was my implementation/limited understanding of exports in ES6.

Here's how I got it to work:

```
let AuthIntercept = require('superagent-intercept')((err, res) => {
  if (res.status === 401) {
    console.log('Unauthorized');
  }
});

export default AuthIntercept;
```
