### ISSUE TITLE
Can't access error properties in rejected promise

### ISSUE THREAD

**Issue by babsonmatt** [KyleAMathews/superagent-bluebird-promise#6]
It appears you can't pass an object directly to Error

https://github.com/babsonmatt/superagent-bluebird-promise/commit/da4ad892f52a1e3c04ab46045e01cb2af0187887

**Comment by KyleAMathews** [comment]
Hrrm... ooops. Fixed that + added some tests to ensure this doesn't happen again. Thanks!
